# Generated by Django 4.1.5 on 2023-01-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rename_order_items_order_order_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
