# Generated by Django 4.1.5 on 2023-02-04 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='image',
            field=models.ImageField(null=True, upload_to='main_category_images/'),
        ),
    ]
