# Generated by Django 4.1.5 on 2023-02-12 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_product_image_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
