# Generated by Django 4.1.5 on 2023-02-12 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_subcategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='brand_images/'),
        ),
        migrations.AddField(
            model_name='brand',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
