# Generated by Django 4.1.5 on 2023-02-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_brand_image_brand_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='slug',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
