# Generated by Django 4.1.5 on 2023-03-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_product_main_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='user',
        ),
        migrations.AddField(
            model_name='vendor',
            name='email',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='full_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='mobile',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
