# Generated by Django 4.1.5 on 2023-03-21 08:32

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_remove_vendor_email_remove_vendor_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
