# Generated by Django 4.1.5 on 2023-04-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_remove_customeraddress_address_customeraddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
